### ISSUE TITLE
Short description is not updated on reimport

### ISSUE THREAD

**Issue by exploide** [ansible/galaxy-issues#116]
Galaxy displays a short description of a role (Details page, right under the heading), similar to what GitHub does with repositories. It seems that the description is indeed copied from the GitHub description.

But when reimporting a role which has a changed short description on GitHub, Galaxy's description is not updated. Moreover, I found no way to change the description on Galaxy.

It would be great if Galaxy could update the short description on a reimport, too. Or, if the two descriptions on Galaxy and GitHub should not be coupled, provide a way to edit it on the Galaxy webpage.

**Comment by chouseknecht** [comment]
The description on Galaxy comes from the meta/main.yml file:

```
---
galaxy_info:
  author: Jannik Vieten
  description:  <<<<---------------
  license: MIT
  min_ansible_version: 1.2
  platforms:
      - name: Fedora
        versions:
        - 23
  galaxy_tags:
    - dnf
    - automatic
    - updates
    - security
    - packaging
    - system

dependencies: []
```
