### ISSUE TITLE
Fedora 24 is marked as invalid

### ISSUE THREAD

**Issue by gbraad** [ansible/galaxy-issues#175]
When using:

```
   platforms:
    - name: Fedora
      versions:
     - 23
     - 24
```

the import marks Fedora-24 as invalid. Below you will find an example of the output

```
Starting import 22520: role_name=firejail repo=gbraad/ansible-role-firejail ref=
Retrieving Github repo gbraad/ansible-role-firejail
Accessing branch: master
Parsing and validating meta/main.yml
Parsing galaxy_tags
Parsing platforms
Invalid platform: Fedora-24 (skipping)
Adding dependencies
Parsing and validating README
Adding repo tags as role versions
Import completed
Status FAILED : warnings=0 errors=1
```
