### ISSUE TITLE
Roles are auto-imported when Travis CI builds fail

### ISSUE THREAD

**Issue by c-mart** [ansible/galaxy-issues#190]
I want Ansible Galaxy to automatically import my roles, but only when the Travis CI build passes. This way, consumers of the role will always get the latest version with passing tests, even if there is a newer version with tests that fail.

Exhibit A, the default webhook configuration, as scaffolded by `ansible-galaxy init` and [Setup Travis Integrations](http://docs.ansible.com/ansible/galaxy.html#setup-travis-integrations) in the docs:

```
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
```

This triggers a Galaxy import every time a Travis CI run finishes, regardless of whether it succeeds or it fails.

Exhibit B, webhook configured according to [Configuring Build Notifications](https://docs.travis-ci.com/user/notifications/#Webhook-notifications) in Travis CI's docs:

```
notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications
    on_success: always
    on_failure: never
```

This _never_ triggers a Galaxy import, regardless of whether the build passes or fails.

It is opaque to me whether this is an Ansible Galaxy issue or a Travis CI issue. It seems like "auto-import only on passing build" should be the default behavior.

**Comment by chouseknecht** [comment]
The mechanism on the Galaxy side for this is `github_branch` in `meta/main.yml`. Set github_branch to the branch that should trigger automatic imports. If no branch is specified, the default is 'master'.

I don't think the issue is the notification from Travis. I'm using the following settings, and I don't see an import firing when the build is broken:

```
notifications:
  webhooks:
    urls:
      - https://galaxy-qa.ansible.com/api/v1/notifications/
    on_failure: never
```

However, even though the import does not fire, the Travis icon within Galaxy changes to `failing`. Galaxy just grabs the status icon for the branch. The URL given to Galaxy by Travis is `https://travis-ci.org/chouseknecht/test-role-1.svg?branch=master`. Notice the `branch` parameter. I don't know how Galaxy would get the most recent successful build, so I think specifying a specific branch is the only way to get what you're asking for.
