### ISSUE TITLE
ansible-galaxy use wrong path when role name contains slashes RoleLib/Role1

### ISSUE THREAD

**Issue by S1y** [ansible/galaxy-issues#226]
# Ansible-Galaxy use wrong path when role name contains slashes `/`

Ansible 2.2.0.0
When importing role from `requirements.yml` with single word role naming,  
a folder named as the role name is created ...  
but when the name contains slashes `/` then all after the first slash is duplicated in the tree !!!.

Examples:
```yaml
  name: RoleLib/Role1
  # lead to RoleLib/Role1/Role1
  name: RoleLib/foo/bar/Role1
  # lead to RoleLib/foo/bar/Role1/foo/bar/Role1
```

I try to google this but found nothing related to this behaviour.
If this is correct, can you explain the purpose of such behaviour when this 

## Context

```console
ansible-galaxy -r requirements.yml
```

Using this `requirements.yml` :
```yaml
- src: git@gitlab:namespace/RoleLib.git
  scm: git
  version: 'master'
  name: RoleLib
```

the RoleLib Gitlab Project :
```console
$ tree roles/
roles/
├── defaults/
│   └── main.yml
├── files/
├── handlers/
│   └── main.yml
├── meta/
│   └── main.yml
├── tasks/
│   └── main.yml
├── templates/
├── tests/
│   ├── inventory
│   └── test.yml
├── vars/
│   └── main.yml
├── README.md
└── .travis.yml
```
File `meta/main.yml` :
```yaml
dependencies:
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  - src: git@gitlab:namespace/RoleLib-Role1.git
    scm: git
    version: 'master'
    name: RoleLib/Role1
```

## Expected behaviour :
The tree command should return :
```console
$ tree roles/
roles/
└── RoleLib/
    ├── defaults/
    │   └── main.yml
    ├── handlers/
    │   └── main.yml
    ├── meta/
    │   ├── .galaxy_install_info
    │   └── main.yml
    ├── Role1/
    │   ├── defaults/
    │   │   └── main.yml
    │   ├── handlers/
    │   │   └── main.yml
    │   ├── meta/
    │   │   ├── .galaxy_install_info
    │   │   └── main.yml
    │   ├── tasks/
    │   │   └── main.yml
    │   ├── tests/
    │   │   ├── inventory
    │   │   └── test.yml
    │   ├── vars/
    │   │   └── main.yml
    │   ├── README.md
    │   └── .travis.yml
    ├── tasks/
    │   └── main.yml
    ├── tests/
    │   ├── inventory
    │   └── test.yml
    ├── vars/
    │   └── main.yml
    ├── README.md
    └── .travis.yml
```

## Actual result :

```console
ansible-galaxy install -r requirements.yml ; tree roles/
- extracting RoleLib to .../roles/RoleLib
- RoleLib was installed successfully
- adding dependency: RoleLib/Role1
- extracting RoleLib/Role1 to .../roles/RoleLib/Role1
ERROR! Unexpected Exception: [Errno 2] No such file or directory: '.../roles/RoleLib/Role1/meta/.galaxy_install_info'
to see the full traceback, use -vvv
roles/
└── RoleLib/
    ├── defaults/
    │   └── main.yml
    ├── handlers/
    │   └── main.yml
    ├── meta/
    │   ├── .galaxy_install_info
    │   └── main.yml
    ├── Role1/
    │   ├── Role1/
    │   │   ├── defaults/
    │   │   │   └── main.yml
    │   │   ├── handlers/
    │   │   │   └── main.yml
    │   │   ├── meta/
    │   │   │   ├── .galaxy_install_info
    │   │   │   └── main.yml
    │   │   ├── tasks/
    │   │   │   └── main.yml
    │   │   ├── tests/
    │   │   │   ├── inventory
    │   │   │   └── test.yml
    │   │   ├── vars/
    │   │   │   └── main.yml
    │   │   └── README.md
    │   └── .travis.yml
    ├── tasks/
    │   └── main.yml
    ├── tests/
    │   ├── inventory
    │   └── test.yml
    ├── vars/
    │   └── main.yml
    ├── README.md
    └── .travis.yml
```
