### ISSUE TITLE
When the platform is 'GenericLinux', the import error occurs

### ISSUE THREAD

**Issue by suzuki-shunsuke** [ansible/galaxy-issues#284]
The platform 'GenericLinux' is included in the [Platform List](https://galaxy.ansible.com/api/v1/platforms/), but on the Ansible Galaxy the following error has occured.

https://galaxy.ansible.com/imports#/?github_user=suzuki-shunsuke&github_repo=ansible-rkt-binary

```
Starting import 136063: role_name=rkt-binary repo=suzuki-shunsuke/ansible-rkt-binary
Accessing branch: master
Parsing and validating meta data.
Parsing galaxy_tags
Parsing platforms
The platform 'GenericLinux' does not appear to be a dictionary, skipping
Parsing and validating README
Adding repo tags as role versions
Removing old tags
Import completed
Status FAILED : warnings=0 errors=1
```

<img width="978" alt="2017-09-24 20 45 53" src="https://user-images.githubusercontent.com/13323303/30782255-6d3a9574-a169-11e7-86cb-e19e690e9e48.png">

**Comment by suzuki-shunsuke** [comment]
This is the meta/main.yml .

https://github.com/suzuki-shunsuke/ansible-rkt-binary/blob/9f696a1e4d954468008f65c0305420964df09b1d/meta/main.yml

```yaml
galaxy_info:
  author: Suzuki Shunsuke
  description: ansible role to install rkt from binary
  license: MIT
  min_ansible_version: 2.2
  github_branch: master
  platforms:
    - GenericLinux
  galaxy_tags:
    - rkt
dependencies: []
```
