### ISSUE TITLE
Best practices for galaxy role dependency variables

### ISSUE THREAD

**Issue by patrickheeney** [ansible/galaxy-issues#61]
Currently role dependencies are the only way to sanely manage a set of interconnected roles. For example, a `sshd` role needs to set `ferm` inputs. However this breaks down, when you need to customize anything. Take the following example for a `sshd` role that has this dependency in `meta/main.yml`:

```
  - role: debops.ferm
    ferm_input_list:
      - type: 'dport_accept'
        dport: '{{ sshd_ferm_ports }}'
        saddr: '{{ sshd_whitelist + sshd_group_whitelist + sshd_host_whitelist }}'
        weight: '25'
        filename: 'sshd_dependency_whitelist'
      - type: 'dport_accept'
        dport: '{{ sshd_ferm_ports }}'
        saddr: '{{ sshd_allow + sshd_group_allow + sshd_host_allow }}'
        weight: '30'
        filename: 'sshd_dependency_accept'
      - type: 'dport_limit'
        dport: '{{ sshd_ferm_ports }}'
        seconds: '{{ sshd_ferm_limit_seconds }}'
        hits: '{{ sshd_ferm_limit_hits }}'
        destination: '{{ sshd_ferm_limit_destination }}'
        syn: True
        weight: '30'
        filename: 'sshd_dependency_limit'
        enabled: '{{ sshd_ferm_limit }}'
```

In this example, how would I remove the `sshd_dependency_whitelist` input. Or perhaps, I want to add another input to the `ferm_input_list` list. Since this is role dependency variable, I can't access any of the `sshd_` variables from another role because they only get loaded in right before it executes. I may also be using tags and these variables would never get set. Another example would be, what if I don't want to use `ferm`, how can this dependency be optional, only if `ferm` is installed?

As you can see, the dependency variables are great, until you need the ability to customize them. Galaxy roles need to have customization because the only alternative is to fork the galaxy role, which defeats the purpose.

I'd like to see if we can come up with any ideas on how to address this at the ansible level, and perhaps document a few best practices for galaxy authors on how to provide this customization.
