### ISSUE TITLE
Galaxy library and plugin dependencies

### ISSUE THREAD

**Issue by patrickheeney** [ansible/galaxy-issues#62]
I have used some galaxy roles before that have failed because they depend on third-party modules or plugins. For example, a `users` role I used required a `ldap` module that was found in another repository. I also used firewall role that required a jinaja2 filter that manipulated an IP. 

I'd like to see the ability for galaxy to download library modules or plugins and install them. The syntax could look something like this when defined in the `meta/main.yml`:

```
dependencies:
  - module: https://github.com/vendor/ansible-ldap/
  - filter_plugin: https://github.com/vendor/ansible-ldap/blob/ipfilter.py
  - role: ansible.galaxy
```

We would need some sort of config or requirements file that perhaps dictated where these would be installed to locally. Ideally the `requirements.yml` could be changed to:

```
modules: 
  - src: https://github.com/vendor/ansible-ldap
    path: ./library

plugins:
  - src: https://github.com/vendor/ansible-ldap/blob/ipfilter.py
    path: vendor/plugins/filters/

roles:
  - ansible.galaxy
```

For backwards compat, all existing galaxy `requirements.yml` files would assume that all entries are `roles` unless `roles` exists. The `path` could be optional and default to the first entry in `ansible.cfg`. 

This opens up a lot of possibilities for galaxy by allowing more advanced roles that depend on functionality outside of ansible. In a perfect world, ansible could be everything to everybody, but allowing this functionality allows galaxy developers to supplement ansible until it can be rolled into core, or maintain a third party module / library that ansible does not wish to support.
