### ISSUE TITLE
Path doesn't work when passed in YAML

### ISSUE THREAD

**Issue by coxley** [ansible/galaxy-issues#91]
``` yaml

---
- src: user.role
  path: ./vendor_roles/
```

The above file ran with `ansible-galaxy install -r Ansiblefile.yml` will still default to `./roles/` which contradicts the [documentation](https://galaxy.ansible.com/intro#download-advanced)
