### ISSUE TITLE
Unknown license in meta/main.yml: FAILED: An unknown error occurred while saving the role.

### ISSUE THREAD

**Issue by ypid** [ansible/galaxy-issues#92]
When trying to re-import a role with an "unknown" license Ansible Galaxy says "FAILED: An unknown error occurred while saving the role. Please wait a few minutes and try again. If you continue to receive a failure, please contact support."
##### Works

``` YAML
license: GPLv3
# license: GPLv3
license: 'something'
license: 'GNU General Public License'
```
##### Does not work

``` YAML
license: 'GNU Affero General Public License'
```
##### Tested with `meta/main.yml`

Fails:

``` YAML

---

dependencies: []

galaxy_info:
  author: 'Robin Schneider'
  description: 'Configure the network traffic monitor vnStat.'
  license: 'GNU Affero General Public License v3'
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - system
  min_ansible_version: 1.3
```
##### Example affected roles
- https://galaxy.ansible.com/detail#/role/2807
- https://galaxy.ansible.com/detail#/role/3778
